version: '3.7'
services:
  features-api:
    # image: "acrpairingchallenge.azurecr.io/api-features-api:latest"
    build: .
    ports:
      - "80:8083"
    command: /features-api --reload
    environment:
      DB_URL: "mongodb://database:27017/pairing-challenge"
    volumes:
      - .:/app
  database:
    image: mongo:latest
    ports:
      - "27017:27017"
    restart: unless-stopped
    volumes:
      - mongodb_data_container:/data/db
  
volumes:
  mongodb_data_container: